##############################################################
# Automatically generated by qmake (1.01a) Wed Jun 19 11:51:48 2002
##############################################################

TEMPLATE = lib
DEPENDPATH += .

# Input
HEADERS += abswag.h\
           advisman.h\
           bemitg.h\
           boundg.h\
           conductg.h\
           controlg.h\
           cylaxisg.h\
           diagg.h\
           diags.h\
           dielecg.h\
           emitprtg.h\
           emitterg.h\
           eportg.h\
           eqpotg.h\
           femitg.h\
           foilg.h\
           gapg.h\
           gridg.h\
           h5diagg.h\
           iloopg.h\
           iregiong.h\
           laserplasmasrcg.h\
           lnchwag.h\
           loadg.h\
           loadpwg.h\
           mccg.h\
           param.h\
           part1g.h\
           particlg.h\
           plsmsrcg.h\
           polarg.h\
           portg.h\
           portgaussg.h\
           portteg.h\
           porttemmwg.h\
           porttmg.h\
           rules.h\
           segmentg.h\
           spatialg.h\
           spboundg.h\
           speciesg.h\
           spemitg.h\
           symmetg.h\
           varg.h\
           varloadg.h\
           vbemitg.h
SOURCES += abswag.cpp\
           advisman.cpp\
           bemitg.cpp\
           boundg.cpp\
           conductg.cpp\
           controlg.cpp\
           cylaxisg.cpp\
           diagg.cpp\
           diags.cpp\
           dielecg.cpp\
           emitprtg.cpp\
           emitterg.cpp\
           eportg.cpp\
           eqpotg.cpp\
           femitg.cpp\
           foilg.cpp\
           gapg.cpp\
           gridg.cpp\
           h5diagg.cpp\
           iloopg.cpp\
           iregiong.cpp\
           laserplasmasrcg.cpp\
           lnchwag.cpp\
           loadg.cpp\
           loadpwg.cpp\
           mccg.cpp\
           param.cpp\
           part1g.cpp\
           particlg.cpp\
           plsmsrcg.cpp\
           polarg.cpp\
           portg.cpp\
           portgaussg.cpp\
           portteg.cpp\
           porttemmwg.cpp\
           porttmg.cpp\
           rules.cpp\
           segmentg.cpp\
           spatialg.cpp\
           speciesg.cpp\
           spemitg.cpp\
           strstuff.cpp\
           varloadg.cpp\
           vbemitg.cpp
INCLUDEPATH=..\xg ..\otools ..\advisor ..\physics  .
CONFIG+=staticlib thread release
win32-borland: QMAKE_CXXFLAGS_RELEASE+=-Pcxx
win32-borland: INCLUDEPATH+=$(BCB)\include 
win32-msvc: QMAKE_CXXFLAGS_RELEASE+=-GX -GR
DEFINES += SCALAR_DOUBLE OPENGL HAVE_OPENGL
win32-msvc: DEFINES += HAVE_STD_STREAMS HAVE_FSTREAM HAVE_OSTREAM HAVE_NONTYPE_TEMPLATE_OPERATORS HAVE_NAMESPACES HAVE_STD_COMPLEX NDEBUG
